extends:
  - stylelint-config-standard
  - '@stylistic/stylelint-config'

plugins:
  - stylelint-no-unsupported-browser-features

rules:
  '@stylistic/indentation':
    - tab

  '@stylistic/declaration-colon-newline-after': null

  declaration-empty-line-before:
    - always
    - except:
        - first-nested
      ignore:
        - after-comment
        - after-declaration

  declaration-block-no-redundant-longhand-properties:
    - true
    - severity: warning

  ## This selectors could not be sorted by specificity:
  # .scrollable { // 0-1-0
  #   table {} // 0-1-1
  # }
  #
  # a + .scrollable, // 0-1-1
  # a + table { // 0-0-2
  # }
  ## Specifity specification: https://www.w3.org/TR/selectors-3/#specificity
  no-descending-specificity: null

  ## https://github.com/stylelint/stylelint/issues/4622
  value-keyword-case:
    - lower
    - ignoreKeywords:
      - BlinkMacSystemFont

  custom-property-empty-line-before: null

  at-rule-no-unknown:
    - true
    - ignoreAtRules:
      - define-mixin
      - mixin

  plugin/no-unsupported-browser-features:
    - true
    - severity: warning

  ## There are variables from `postcss-mixins`
  function-no-unknown: null

overrides:
  - files:
      - '**/*.pcss'
    rules:
      plugin/no-unsupported-browser-features:
        - true
        - ignore:
          - css-nesting
